name: Fossa

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:

  scan:
    name: Fossa
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Scan
        uses: fossas/fossa-action@v1
        with:
          api-key: ${{ secrets.FOSSA_TOKEN }}
